# Generated by Django 4.2.29 on 2026-04-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_color', models.CharField(default='#ffffff', max_length=20)),
                ('font_family', models.CharField(default='Arial, sans-serif', max_length=50)),
            ],
        ),
    ]
