# Generated by Django 4.2.29 on 2026-04-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webstyle',
            name='secondary_color',
            field=models.CharField(default='#4f46e5', max_length=20),
        ),
        migrations.AlterField(
            model_name='webstyle',
            name='bg_color',
            field=models.CharField(default='#f3f4f6', max_length=20),
        ),
        migrations.AlterField(
            model_name='webstyle',
            name='font_family',
            field=models.CharField(default='ui-sans-serif, system-ui, sans-serif', max_length=255),
        ),
    ]
