# Generated by Django 4.2.29 on 2026-04-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_webstyle_secondary_color_alter_webstyle_bg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webstyle',
            name='btn_text_color',
            field=models.CharField(default='#ffffff', max_length=20),
        ),
    ]
