# Generated by Django 4.2.29 on 2026-04-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_webstyle_btn_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='webstyle',
            name='text_color',
            field=models.CharField(default='#1f2937', max_length=20),
        ),
    ]
